name: BCOM
favicon: null
layout_spectrum: 0.5095250564627349
typography_spectrum: 0.6838073753751814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3541988080833107
  lightness: 0.24992731725797057
  saturation: 0.9546457030810416
  rhythmicContrast: 0.1263602019753307
purpose: []
